services:
  ezgramwatch:
    image: ghcr.io/slgfire/ezgramwatch:latest
    container_name: ezgramwatch
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/data
    user: "root"
